<?php

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

declare(strict_types=1);

use Kitsune\Core\Media\MediaIntake;

/*
 * What core accepts as an upload, and what it refuses — ADR-041.
 *
 * ⚠️ THESE ARE THE SECURITY TESTS, and they are written first for that reason: a mistake here is a
 * vulnerability rather than a bug. Nothing in this repository covered upload safety before ADR-041 —
 * `field-types.md` §6 names `rich_text` and `json` as "the two types that need security review", and an
 * uploaded file is neither.
 */

/** A real file on disk, because every check reads bytes rather than trusting a name. */
function fileHolding(string $bytes, string $suffix = ''): string
{
    $path = tempnam(sys_get_temp_dir(), 'kitsune-intake-').$suffix;
    file_put_contents($path, $bytes);

    return $path;
}

/** The smallest valid PNG: an 8-byte signature is enough for finfo to call it image/png. */
function pngBytes(): string
{
    return base64_decode(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='
    );
}

afterEach(function (): void {
    foreach (glob(sys_get_temp_dir().'/kitsune-intake-*') ?: [] as $leftover) {
        @unlink($leftover);
    }
});

it('accepts a genuine png named as one', function (): void {
    $path = fileHolding(pngBytes());

    expect(MediaIntake::accept('photo.png', $path, filesize($path)))
        ->toBe(['extension' => 'png', 'mime' => 'image/png']);
});

/**
 * ⚠️ THE CLASSIC HOLE, IN BOTH DIRECTIONS. An extension allowlist alone accepts a script named `.jpg`; a MIME
 * check alone accepts a genuine image named `.php`, which some server configurations will execute. The pair
 * must agree, so both halves are asserted rather than one.
 */
it('refuses a php script wearing an image extension', function (): void {
    $path = fileHolding("<?php echo 'pwned'; ?>\n");

    expect(fn () => MediaIntake::accept('innocent.png', $path, filesize($path)))
        ->toThrow(RuntimeException::class, 'its contents are');
});

it('refuses a genuine png wearing a php extension', function (): void {
    $path = fileHolding(pngBytes());

    expect(fn () => MediaIntake::accept('payload.php', $path, filesize($path)))
        ->toThrow(RuntimeException::class, 'not an accepted file type');
});

it('refuses a file with no extension at all', function (): void {
    $path = fileHolding(pngBytes());

    expect(fn () => MediaIntake::accept('README', $path, filesize($path)))
        ->toThrow(RuntimeException::class, 'no extension');
});

/** ADR-041 accepts SVG — sanitised. Until the sanitiser exists it is refused rather than stored unsanitised. */
it('refuses svg until the sanitiser ships with it', function (): void {
    $path = fileHolding('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>');

    expect(fn () => MediaIntake::accept('logo.svg', $path, filesize($path)))
        ->toThrow(RuntimeException::class, 'not an accepted file type');
});

it('refuses a file over the ceiling before anything is written', function (): void {
    $path = fileHolding(pngBytes());

    expect(fn () => MediaIntake::accept('huge.png', $path, MediaIntake::MAX_BYTES + 1))
        ->toThrow(RuntimeException::class, 'the ceiling is');
});

/*
 * ⚠️ A CALLER'S FILENAME NEVER BECOMES A PATH.
 *
 * Traversal, a leading slash, a Windows separator, a null byte and a name that is nothing but dots are the
 * same problem wearing different clothes: the uploader choosing where bytes land or what they overwrite. The
 * extension is read from the basename, and the stored name is generated by core.
 */
it('takes the extension from the basename, whatever the path pretends to be', function (string $name): void {
    expect(MediaIntake::extensionOf($name))->toBe('png');
})->with([
    'traversal' => '../../../etc/passwd.png',
    'absolute' => '/etc/cron.d/evil.png',
    'windows separator' => 'C:\\windows\\system32\\evil.png',
    'nested' => 'a/b/c/photo.PNG',
    'uppercase' => 'PHOTO.PNG',
]);

it('generates a stored name that carries nothing from the caller', function (): void {
    $stored = MediaIntake::storedName('png');

    expect($stored)->toEndWith('.png')
        ->and($stored)->toMatch('/^[0-9a-f]{32}\.png$/')
        /* Nothing a caller could have supplied survives into the name bytes are written under. */
        ->and($stored)->not->toContain('/')
        ->and($stored)->not->toContain('..');
});

it('never generates the same stored name twice', function (): void {
    $names = array_map(fn (): string => MediaIntake::storedName('png'), range(1, 50));

    expect(array_unique($names))->toHaveCount(50);
});

/** An allowlist, never a denylist — the rule `rich_text` already follows, asserted so it cannot quietly invert. */
it('publishes an allowlist whose every entry pins its accepted content types', function (): void {
    expect(MediaIntake::ACCEPTED)->not->toBeEmpty();

    foreach (MediaIntake::ACCEPTED as $extension => $mimes) {
        expect($extension)->toMatch('/^[a-z0-9]+$/')
            ->and($mimes)->not->toBeEmpty();

        foreach ($mimes as $mime) {
            expect($mime)->toMatch('#^[a-z]+/[a-z0-9.+-]+$#');
        }
    }

    /* The executable extensions that must never appear, asserted by name rather than by reading the list. */
    foreach (['php', 'phtml', 'phar', 'svg', 'html', 'htm', 'js', 'sh', 'exe'] as $forbidden) {
        expect(MediaIntake::ACCEPTED)->not->toHaveKey($forbidden);
    }
});
